In [29]:
import pandas as pd

In [30]:
import numpy as np

In [6]:
df = pd.read_csv('pokemon.csv')

In [33]:
df

,Pokemon_ID,Name,Type,HP,Attack,Defense,Speed,Legendary
0,1,Bulbasaur,Grass,45,49,49,45,False
1,2,Ivysaur,Grass,60,62,63,60,False
2,3,Venusaur,Grass,80,82,83,80,False
3,3,VenusaurMega Venusaur,Grass,80,100,123,80,False
4,4,Charmander,Fire,39,52,43,65,False
5,5,Charmeleon,Fire,58,64,58,80,False
6,6,Charizard,Fire,78,84,78,100,False
7,6,CharizardMega Charizard X,Fire,78,130,111,100,False
8,6,CharizardMega Charizard Y,Fire,78,104,78,100,False
9,7,Squirtle,Water,44,48,65,43,False
10,8,Wartortle,Water,59,63,80,58,False
11,9,Blastoise,Water,79,83,100,78,False
12,9,BlastoiseMega Blastoise,Water,79,103,120,78,False
13,10,Caterpie,Bug,45,30,35,45,False
14,11,Metapod,Bug,50,20,55,30,False
15,12,Butterfree,Bug,60,45,50,70,False
16,13,Weedle,Bug,40,35,30,50,False
17,14,Kakuna,Bug,45,25,50,35,False
18,15,Beedrill,Bug,65,90,40,75,False
19,15,BeedrillMega Beedrill,Bug,65,150,40,145,False
20,16,Pidgey,Normal,40,45,40,56,False
21,17,Pidgeotto,Normal,63,60,55,71,False
22,18,Pidgeot,Normal,83,80,75,101,False
23,18,PidgeotMega Pidgeot,Normal,83,80,80,121,False
24,19,Rattata,Normal,30,56,35,72,False
25,20,Raticate,Normal,55,81,60,97,False
26,21,Spearow,Normal,40,60,30,70,False
27,22,Fearow,Normal,65,90,65,100,False
28,23,Ekans,Poison,35,60,44,55,False
29,24,Arbok,Poison,60,85,69,80,False
...,...,...,...,...,...,...,...,...
770,700,Sylveon,Fairy,95,65,65,60,False
771,701,Hawlucha,Fighting,78,92,75,118,False
772,702,Dedenne,Electric,67,58,57,101,False
773,703,Carbink,Rock,50,50,150,50,False
774,704,Goomy,Dragon,45,50,35,40,False
775,705,Sliggoo,Dragon,68,75,53,60,False
776,706,Goodra,Dragon,90,100,70,80,False
777,707,Klefki,Steel,57,80,91,75,False
778,708,Phantump,Ghost,43,70,48,38,False
779,709,Trevenant,Ghost,85,110,76,56,False
780,710,PumpkabooAverage Size,Ghost,49,66,70,51,False
781,710,PumpkabooSmall Size,Ghost,44,66,70,56,False
782,710,PumpkabooLarge Size,Ghost,54,66,70,46,False
783,710,PumpkabooSuper Size,Ghost,59,66,70,41,False
784,711,GourgeistAverage Size,Ghost,65,90,122,84,False
785,711,GourgeistSmall Size,Ghost,55,85,122,99,False
786,711,GourgeistLarge Size,Ghost,75,95,122,69,False
787,711,GourgeistSuper Size,Ghost,85,100,122,54,False
788,712,Bergmite,Ice,55,69,85,28,False
789,713,Avalugg,Ice,95,117,184,28,False
790,714,Noibat,Flying,40,30,35,55,False
791,715,Noivern,Flying,85,70,80,123,False
792,716,Xerneas,Fairy,126,131,95,99,True
793,717,Yveltal,Dark,126,131,95,99,True
794,718,Zygarde50% Forme,Dragon,108,100,121,95,True
795,719,Diancie,Rock,50,100,150,50,True
796,719,DiancieMega Diancie,Rock,50,160,110,110,True
797,720,HoopaHoopa Confined,Psychic,80,110,60,70,True
798,720,HoopaHoopa Unbound,Psychic,80,160,60,80,True
799,721,Volcanion,Fire,80,110,120,70,True

In [9]:
df.head()

,Pokemon_ID,Name,Type,HP,Attack,Defense,Speed,Legendary
0,1,Bulbasaur,Grass,45,49,49,45,False
1,2,Ivysaur,Grass,60,62,63,60,False
2,3,Venusaur,Grass,80,82,83,80,False
3,3,VenusaurMega Venusaur,Grass,80,100,123,80,False
4,4,Charmander,Fire,39,52,43,65,False

In [10]:
df.tail()

,Pokemon_ID,Name,Type,HP,Attack,Defense,Speed,Legendary
795,719,Diancie,Rock,50,100,150,50,True
796,719,DiancieMega Diancie,Rock,50,160,110,110,True
797,720,HoopaHoopa Confined,Psychic,80,110,60,70,True
798,720,HoopaHoopa Unbound,Psychic,80,160,60,80,True
799,721,Volcanion,Fire,80,110,120,70,True

In [50]:
grass_df = df.copy()
grass_df = grass_df[grass_df['Type'] == 'Grass']
grass_df_HP50 = grass_df[grass_df['HP'] >= 50]
grass_df_HP50.describe()

       Pokemon_ID          HP      Attack     Defense       Speed
count   57.000000   57.000000   57.000000   57.000000   57.000000
mean   351.403509   73.157895   80.789474   75.368421   66.245614
std    201.720445   16.574280   21.538783   23.881128   28.866244
min      2.000000   50.000000   40.000000   35.000000   15.000000
25%    188.000000   60.000000   62.000000   60.000000   46.000000
50%    387.000000   70.000000   80.000000   72.000000   60.000000
75%    497.000000   80.000000  100.000000   85.000000   83.000000
max    673.000000  123.000000  132.000000  131.000000  145.000000

In [43]:
grass_fire_water_df = df.copy()
interest = ['Grass', 'Water', 'Fire']
grass_fire_water_df = grass_fire_water_df[grass_fire_water_df['Type'].isin(interest)]
grass_fire_water_df.groupby('Type').size().reset_index(name= "No. of Pokemons")

    Type  No. of Pokemons
0   Fire               52
1  Grass               70
2  Water              112